// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:online_shop/models/orders/sneakers.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'general.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'general.g.dart';

@freezed
class GeneralModel with _$GeneralModel {
  const factory GeneralModel({
    required bool? success,
    required int? statusCode,
    required String? message,
    required List<StoreProduct> data,
  }) = _GeneralModel;

  factory GeneralModel.fromJson(Map<String, Object?> json)
  => _$GeneralModelFromJson(json);
}