// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:online_shop/models/orders/size.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sneakers.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'sneakers.g.dart';

@freezed
class Sneakers with _$Sneakers {
  const factory Sneakers({
    // required String id,
    required List<String> images,
    required int? stock,
    required String? name,
    required String? title,
    required String? category,
    // required List<String> imageUrl,
    required String? oldPrice,
    required bool? isSelected,
    // required List<Size> sizes,
    required int? price,
    required String? description,
    // required int v,
  }) = _Sneakers;

  factory Sneakers.fromJson(Map<String, Object?> json)
  => _$SneakersFromJson(json);
}