// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:online_shop/models/orders/sneakers.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    required String? id,
    required String? username,
    required String? email,
  }) = _User;


  factory User.fromJson(Map<String, Object?> json)
  => _$UserFromJson(json);
}